version: '3.8'

services:
  whisper_asr_node:
    image: whisper_asr_node
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile_whisper_asr
    container_name: whisper_asr_node
    environment:
      - COMPUTER_ROLE=${COMPUTER_ROLE}
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_IP=127.0.0.1
    network_mode: host
    volumes:
      - "${LOCAL_ROS_WS}:/root/ros2_ws/src/speech-llm-speech"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  google_tts_node:
    image: naren200/google_tts_node:v1
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile_google_tts
    container_name: google_tts_node
    environment:
      - COMPUTER_ROLE=${COMPUTER_ROLE}
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_IP=127.0.0.1
    network_mode: host
    volumes:
      - "${LOCAL_ROS_WS}:/root/ros2_ws/src/speech-llm-speech/google_tts"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    init: true
    ports:
      - "11434:11434"
    privileged: true
    stdin_open: true
    tty: true

  decision_maker_node:
    image: decision_maker_node
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile_decision_maker
    container_name: decision_maker_node
    environment:
      - COMPUTER_ROLE=${COMPUTER_ROLE}
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_IP=127.0.0.1
    network_mode: host
    volumes:
      - "${LOCAL_ROS_WS}:/root/ros2_ws/src/speech-llm-speech"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
