FROM ubuntu:22.04


# Specify bash as the shell for RUN commands
SHELL ["/bin/bash", "-c"]

# Set environment variables
ENV TZ='America/New_York' \
    DEBIAN_FRONTEND=noninteractive \
    ROS_DISTRO=iron 

# Install basic dependencies and set up ROS 2 repositories
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    software-properties-common \
    gnupg \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Install system dependencies and ROS 2 packages
RUN apt-get update && apt-get install -y \
    git \
    locales \
    python3-colcon-common-extensions \
    ros-iron-ament-cmake \
    ros-iron-ament-cmake-auto \
    libcurl4-openssl-dev \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Configure locale
RUN locale-gen en_US en_US.UTF-8 \
    && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

# Install ROS2
RUN apt-get update && add-apt-repository universe \
    && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null \
    && apt-get update -y \
    && apt-get install -y ros-${ROS_DISTRO}-desktop ros-dev-tools \
    && rm -rf /var/lib/apt/lists/*

# Source the ROS 2 setup script
RUN apt-get update && apt-get install -y \
    && source /opt/ros/${ROS_DISTRO}/setup.bash

# Configure ROS2 environment
RUN echo "source /opt/ros/iron/setup.bash" >> ~/.bashrc \
    && echo "export ROS_DOMAIN_ID=0" >> ~/.bashrc


# Set up workspace
WORKDIR /root/ros2_ws
RUN mkdir -p /root/ros2_ws/src/speech-llm-speech/google_tts
COPY . /root/ros2_ws/src/speech-llm-speech/google_tts/.
# COPY . /root/ros2_ws/src/speech-llm-speech/

# Install gtts using pip3
RUN pip3 install gtts && \
    pip3 install flask && \
    pip3 install flask_cors 


# Navigate to the workspace
WORKDIR /root/ros2_ws
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3-colcon-core \
    ros-iron-ament-cmake \
    && source /opt/ros/iron/setup.bash \


CMD ["/bin/bash", "-l"]